# Generated by Django 6.0.2 on 2026-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='abstract_course',
            field=models.CharField(default='Trilha Geral', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='learning_mode',
            field=models.CharField(choices=[('in_person', 'Presencial'), ('remote', 'Remoto')], default='in_person', max_length=12),
        ),
    ]
