# Generated by Django 6.0.2 on 2026-03-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_abstract_course_student_learning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='learning_mode',
            field=models.CharField(choices=[('in_person', 'Presencial'), ('remote', 'Remota')], default='in_person', max_length=12),
        ),
    ]
