# Generated by Django 6.0.2 on 2026-03-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolclass_learning_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=30, unique=True)),
                ('subject', models.CharField(max_length=180)),
                ('sector', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em andamento'), ('completed', 'Concluido')], default='open', max_length=20)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['deadline', 'protocol'],
            },
        ),
        migrations.CreateModel(
            name='ManagementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('owner', models.CharField(max_length=150)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Em execucao'), ('approved', 'Aprovado')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('central', 'Central de Servicos'), ('it', 'Tec. da Informacao'), ('security', 'Seguranca Institucional'), ('admin', 'Administracao')], max_length=20)),
                ('requester', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=180)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('working', 'Em atendimento'), ('resolved', 'Resolvido')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('project_type', models.CharField(choices=[('research', 'Pesquisa'), ('extension', 'Extensao'), ('international', 'Internacionalizacao'), ('development', 'Desenvolvimento Institucional'), ('student', 'Atividades Estudantis'), ('communication', 'Comunicacao Social'), ('audit', 'Auditoria')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Planejamento'), ('active', 'Em execucao'), ('closed', 'Concluido')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'ordering': ['project_type', 'title'],
            },
        ),
    ]
